version: 2.1
orbs:
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@1.0.5

jobs:
  test:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - node/install:
          node-version: 18.10.0
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test && npm run coverage > ./coverage/lcov.info
          name: Run tests
      - persist_to_workspace:
          root: ~/
          paths:
            - "project"

  done:
    working_directory: ~/project
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/
      - coveralls/upload

workflows:
  test-cover:
    jobs:
      - test
      - done:
          requires:
            - test
